trigger:
- main
variables:
  buildConfiguration: 'Release'
  webTailspinRepository: 'lijcam/space-game-web'
  webLeaderboardRepository: 'lijcam/space-game-leaderboard'
  tag: '$(Build.BuildId)'
  vmImage: 'ubuntu-20.04'

stages:
- stage: 'SecOps_Scan'
  jobs:
    - job: 'RunScan'
      displayName: 'Running DevSecOps Scan'
      pool:
        vmImage: $(vmImage)
      steps:
      - task: MicrosoftSecurityDevOps@1
        displayName: 'Execute default all scan'
        inputs:
          break: false
- stage: 'Build_Containers'
  displayName: 'Build and Push Space Game Containers'
  dependsOn: 'SecOps_Scan'
  jobs:  
  - job: 'BuildTailspin'
    displayName: 'Build Tailspin Container Image'
    pool:
      vmImage: $(vmImage)
    steps:
    - task: Docker@2
      displayName: Login
      inputs:
        command: login
        containerRegistry: 'Space Game Service Connection'
    - task: Docker@2
      displayName: 'Build and push tailspin image to container registry'
      inputs:
        command: buildAndPush
        buildContext: '$(Build.Repository.LocalPath)/Tailspin.SpaceGame.Web'
        repository: $(webTailspinRepository)
        dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Dockerfile'
        #containerRegistry: 'Space Game Service Connection'
        tags: |
          $(tag)
  - job: 'BuildLeaderboard'
    dependsOn: 'BuildTailspin'
    displayName: 'Build Leaderboard Container Image'
    pool:
      vmImage: $(vmImage)
    steps:
    - task: Docker@2
      displayName: Login
      inputs:
        command: login
        containerRegistry: 'Space Game Service Connection'
    - task: Docker@2
      displayName: 'Build and push leaderboard image to container registry'
      inputs:
        command: buildAndPush
        buildContext: '$(Build.Repository.LocalPath)/Tailspin.SpaceGame.LeaderboardContainer'
        repository: $(webLeaderboardRepository)
        dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.LeaderboardContainer/Dockerfile'
        #containerRegistry: 'Space Game Service Connection'
        tags: |
          $(tag)
