trigger: none

variables:
  buildConfiguration: 'Release'
  webRepository: 'web'
  tag: '$(Build.BuildId)'
  vmImage: 'ubuntu-20.04'

stages:
- stage: 'Build Containers'
  displayName: 'Build and push'
  jobs:  
  - job: 'BuildTailspin'
    displayName: 'Build Tailspin Container Image'
    pool:
      vmImage: $(vmImage)
    steps:
    - task: Docker@2
      displayName: 'Build and push tailspin image to container registry'
      inputs:
        command: buildAndPush
        buildContext: '$(Build.Repository.LocalPath)/Tailspin.SpaceGame.Web'
        repository: $(webRepository)
        dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Dockerfile'
        containerRegistry: 'Space Game Service Connection'
        tags: |
          $(tag)
  - job: 'BuildLeaderboard'
    dependsOn: 'BuildTailspin'
    displayName: 'Build Leaderboard Container Image'
    pool:
      vmImage: $(vmImage)
    steps:
    - task: Docker@2
      displayName: 'Build and push leaderboard image to container registry'
      inputs:
        command: buildAndPush
        buildContext: '$(Build.Repository.LocalPath)/Tailspin.SpaceGame.LeaderboardContainer'
        repository: $(webRepository)
        dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.LeaderboardContainer/Dockerfile'
        containerRegistry: 'Space Game Leaderboard Service Connection'
        tags: |
          $(tag)
