trigger: none

variables:
  buildConfiguration: 'Release'
  webRepository: 'web'
  tag: '$(Build.BuildId)'
  WebAppName: 'Tailspin Space Game'

stages:
- stage: 'Build'
  displayName: 'Build and push'
  jobs:
  - job:
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Space Game Service Connection'
        repository: '$(webRepository)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'
        tags: |
          $(tag)

#- stage: 'Deploy'
#  displayName: 'Deploy the container'
#  dependsOn: Build
#  jobs:
# - job: 'Deploy'
#    displayName: 'Deploy job'
#    pool:
#      vmImage: 'ubuntu-20.04'
#    variables:
#    - group: Release
#    steps:
#    - task: AzureWebAppContainer@1
#      inputs:
#       appName: $(WebAppName)
#       azureSubscription: 'Resource Manager - Tailspin - Space Game'
#       imageName: $(RegistryName)/$(webRepository):$(build.buildId) ##
