trigger: none

variables:
  buildConfiguration: 'Release'
  webRepository: 'web'
  tag: '$(Build.BuildId)'
  WebAppName: 'Tailspin Space Game'

stages:
- stage: 'Build'
  displayName: 'Build and push'
  jobs:
  - job:
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo $(Build.Repository.LocalPath)   
    - task: Docker@2
      inputs:
        containerRegistry: 'Space Game Service Connection'
        repository: '$(webRepository)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'
        tags: |
          $(tag)